// SnapBoard API — this is already built for you. Do NOT edit this file.
// It gives you: POST /auth/login, an authenticated POST /api/upload (multer),
// and static serving of /uploads. Your work is entirely on the React client.

const path = require("path");
const express = require("express");
const cors = require("cors");
const multer = require("multer");
const jwt = require("jsonwebtoken");

const app = express();
const PORT = process.env.PORT || 3001;
const JWT_SECRET = process.env.JWT_SECRET || "snapboard-dev-secret";

app.use(cors()); // allow the Vite dev server (http://localhost:5173) to call us
app.use(express.json());

// ── Demo accounts (password is "password" for both) ──────────────────────────
const USERS = {
  "ada@demo.com": { id: "u1", name: "Ada Lovelace", role: "admin" },
  "grace@demo.com": { id: "u2", name: "Grace Hopper", role: "user" },
};

// POST /auth/login → { accessToken, user }
app.post("/auth/login", (req, res) => {
  const { email, password } = req.body || {};
  const user = USERS[email];
  if (!user || password !== "password") {
    return res.status(401).json({ message: "Invalid email or password" });
  }
  const accessToken = jwt.sign(user, JWT_SECRET, { expiresIn: "1h" });
  res.json({ accessToken, user });
});

// verifyToken middleware
function verifyToken(req, res, next) {
  const header = req.headers.authorization || "";
  const token = header.startsWith("Bearer ") ? header.slice(7) : null;
  if (!token) return res.status(401).json({ message: "No token provided" });
  try {
    req.user = jwt.verify(token, JWT_SECRET);
    next();
  } catch {
    return res.status(401).json({ message: "Invalid or expired token" });
  }
}

// ── File upload (multer): images only, 5MB max ───────────────────────────────
const storage = multer.diskStorage({
  destination: "uploads/",
  filename: (req, file, cb) => {
    const unique = `${Date.now()}-${Math.round(Math.random() * 1e9)}`;
    cb(null, `photo-${unique}${path.extname(file.originalname)}`);
  },
});
const upload = multer({
  storage,
  limits: { fileSize: 5 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
    const ok = ["image/jpeg", "image/png", "image/webp", "image/gif"];
    cb(null, ok.includes(file.mimetype));
  },
});

// POST /api/upload  (auth required, field name: "image")
app.post("/api/upload", verifyToken, upload.single("image"), (req, res) => {
  if (!req.file) return res.status(400).json({ message: "No image uploaded" });
  res.status(201).json({ url: `/uploads/${req.file.filename}`, uploadedBy: req.user.name });
});

app.use("/uploads", express.static("uploads"));

app.listen(PORT, () => console.log(`SnapBoard API on http://localhost:${PORT}`));
